# Generated by Django 6.0.4 on 2026-05-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('single_transfer_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allows_overdraft', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='customer.bankaccounttype'),
        ),
    ]
