# Generated by Django 6.0.4 on 2026-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_bankaccounttype_alter_userbankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique account number', max_length=20, unique=True, verbose_name='account number'),
        ),
    ]
