# Generated by Django 6.0.4 on 2026-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_userbankaccount_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('card_type', models.CharField(choices=[('visa', 'Visa Debit Card'), ('master', 'Master Debit Card')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound')], default='USD', max_length=10)),
                ('spending_limit', models.DecimalField(decimal_places=2, help_text='Daily or monthly spending limit', max_digits=12)),
                ('issuance_fee', models.CharField(choices=[('5', 'Standard - $5.00'), ('15', 'Gold - $15.00'), ('25', 'Platinum - $25.00'), ('50', 'Black - $50.00')], default='5', max_length=10)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Branch Pickup'), ('home_delivery', 'Home Delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
