# Generated by Django 6.0.4 on 2026-05-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_debitcardapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcardapplication',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='debit_card_applications', to='customer.userbankaccount'),
            preserve_default=False,
        ),
    ]
