# Generated by Django 6.0.4 on 2026-05-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_debitcardapplication_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('standard', 'Standard Debit Card'), ('gold', 'Gold Debit Card'), ('platinum', 'Platinum Debit Card'), ('black', 'Black Debit Card')], default='standard', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('AED', 'AED - UAE Dirham'), ('KWD', 'KWD - Kuwaiti Dinar')], default='USD', max_length=10)),
                ('card_number', models.CharField(editable=False, max_length=19, unique=True)),
                ('card_holder_name', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('issuance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_virtual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='customer.userbankaccount')),
            ],
        ),
    ]
