# Generated by Django 6.0.4 on 2026-05-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_debitcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa Debit Card'), ('master', 'Master Debit Card')], default='visa', max_length=20),
        ),
    ]
