# Generated by Django 6.0.4 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_debitcard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcardapplication',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('AED', 'AED - UAE Dirham'), ('KWD', 'KWD - Kuwaiti Dinar')], default='USD', max_length=10),
        ),
    ]
