# Generated by Django 6.0.4 on 2026-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_debitcardapplication_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='transaction_status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=10),
        ),
    ]
