# Generated by Django 6.0.4 on 2026-05-11 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycverification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kycverification', to=settings.AUTH_USER_MODEL),
        ),
    ]
