# Generated by Django 6.0.4 on 2026-05-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycverification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
