# Generated by Django 6.0.4 on 2026-05-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='passport_photograph',
            field=models.ImageField(upload_to='kyc/passport/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='upload_back_side',
            field=models.ImageField(upload_to='kyc/back/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='upload_front_side',
            field=models.ImageField(upload_to='kyc/front/'),
        ),
    ]
